name: macOS ramtest
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  windows:
    runs-on: windows-latest
    outputs:
      size: ${{ steps.testwin.outputs.ramsize }}
    steps:
    - id: testwin
      shell: pwsh
      run: |
          $ramsize = $(Get-WMIObject win32_ComputerSystem | foreach {[math]::truncate($_.TotalPhysicalMemory)})
          echo "ramsize=${ramsize}" >> $env:GITHUB_OUTPUT

  linux:
    runs-on: ubuntu-latest
    outputs:
      size: ${{ steps.testlinux.outputs.ramsize }}
    steps:
    - id: testlinux
      run: |
        ramsize=$(grep MemTotal /proc/meminfo | cut -f2 -d':' | cut -f8 -d' ')
        echo "ramsize=$ramsize" >> "$GITHUB_OUTPUT"
        
  intel:
    runs-on: macos-13
    outputs:
      size: ${{ steps.testintelmac.outputs.ramsize }}
    steps:
    - id: testintelmac
      run: |
        zsh
        hwmemsize=$(sysctl -n hw.memsize)
        ramsize=$(expr $hwmemsize / $((1073741824.)))
        echo "ramsize=$ramsize" >> $GITHUB_OUTPUT
        exit
        
  arm64:
    runs-on: macos-14
    needs: [intel, windows, linux]
    env:
      INTEL_RAM: ${{ needs.intel.outputs.size }}
      LINUX_RAM: ${{ needs.linux.outputs.size }}
      WINDOWS_RAM: ${{ needs.windows.outputs.size }}
    steps:
    - name: Test RAM on arm64
      run: |
        zsh
        hwmemsize=$(sysctl -n hw.memsize)
        ramsize=$(expr $hwmemsize / $((1073741824.)))
  
        echo "<hr>" \
        "**mac-arm64** RAM: ${ramsize} GB<br>" \
        "**mac-intel** RAM: $INTEL_RAM GB<br>" \
        "**windows**   RAM: $(expr $WINDOWS_RAM / $((1073741824.))) GB<br>" \
        "**linux**     RAM: $(wxpr $LINUX_RAM / $((1048576.0))) GB<br><hr>" >> $GITHUB_STEP_SUMMARY
        exit
