name: macOS ramtest
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  windows:
    runs-on: windows-latest
    outputs:
      size: ${{ steps.testwin.outputs.ramsize }}
    steps:
    - id: testwin
      shell: pwsh
      run: |
          $ramsize = $(Get-WMIObject win32_ComputerSystem | foreach {[math]::truncate($_.TotalPhysicalMemory)})
          echo "ramsize=${ramsize}" >> $env:GITHUB_OUTPUT

  linux:
    runs-on: ubuntu-latest
    outputs:
      size: ${{ steps.testlinux.outputs.ramsize }}
    steps:
    - id: testlinux
      run: |
        ramsize=$(grep MemTotal /proc/meminfo | cut -f2 -d':' | cut -f8 -d' ')
        echo "ramsize=$ramsize" >> "$GITHUB_OUTPUT"
        
  intel:
    runs-on: macos-13
    outputs:
      size: ${{ steps.testintelmac.outputs.ramsize }}
    steps:
    - id: testintelmac
      run: |
        hwmemsize=$(sysctl -n hw.memsize)
        ramsize=$(mem=$hwmemsize zsh -c 'ramsize=$(($mem / $((1073741824.0)))) && echo $ramsize')
        echo "ramsize=$ramsize" >> $GITHUB_OUTPUT
        
  arm64:
    runs-on: macos-14
    needs: [intel, windows, linux]
    env:
      INTEL_RAM: ${{ needs.intel.outputs.size }}
      LINUX_RAM: ${{ needs.linux.outputs.size }}
      WINDOWS_RAM: ${{ needs.windows.outputs.size }}
    steps:
    - name: Test RAM on arm64
      run: |
        hwmemsize=$(sysctl -n hw.memsize)
        ramsize=$(printf "%.3f" $(mem=$hwmemsize zsh -c 'ramsize=$(($mem / $((1073741824.0)))) && echo $ramsize'))
        linuxsize=$(printf "%.3f" $(mem=$LINUX_RAM zsh -c 'echo $(($mem / $((1048576.0))))'))
        winsize=$(printf "%.3f" $(mem=$WINDOWS_RAM zsh -c 'echo $(($mem / $((1073741824.0))))'))
        intelsize=$(printf '%.3f' "$INTEL_RAM")
        echo "
        
        ---
        
        **mac-arm64** RAM: ${ramsize} GB
        **mac-intel** RAM: ${intelsize} GB
        **windows**   RAM: ${winsize} GB
        **linux**     RAM: ${linuxsize} GB
        
        ---
        
        " >> $GITHUB_STEP_SUMMARY
        exit
