name: macOS ramtest
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  intel:
    runs-on: macos-13
    steps:
      - name: Test RAM on intel
        run: |
          hwmemsize=$(sysctl -n hw.memsize)
          # 1024**3 = GB
          ramsize=$(expr $hwmemsize / $((1024**3)))

  arm64:
    runs-on: macos-14
    needs: intel
    env:
      INTEL_RAM: ${{ jobs.intel.outputs.ramsize }}
    steps:
    - name: Test RAM on arm64
      run: |
        hwmemsize=$(sysctl -n hw.memsize)
        # 1024**3 = GB
        ramsize=$(expr $hwmemsize / $((1024**3)))
        echo "arm64 RAM: ${ramsize} GB"
        echo "intel RAM: $INTEL_RAM GB"
