name: macOS ramtest
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  windows:
    runs-on: windows-latest
    outputs:
      size: ${{ steps.testwin.outputs.ramsize }}
    steps:
    - id: testwin
      shell: pwsh
      run: |
          $ramsize = $(Get-WMIObject win32_ComputerSystem | foreach {[math]::truncate($_.TotalPhysicalMemory /1GB)})
          echo "ramsize=${ramsize}" >> $env:GITHUB_OUTPUT

  linux:
    runs-on: ubuntu-latest
    outputs:
      size: ${{ steps.testlinux.outputs.ramsize }}
    steps:
    - id: testlinux
      run: |
        zsh
        ramsize=$[$[$(grep MemTotal /proc/meminfo | cut -f2 -d':' | cut -f8 -d' ')] / 1048576]
        echo "ramsize=$ramsize" >> "$GITHUB_OUTPUT"
        exit
  intel:
    runs-on: macos-13
    outputs:
      size: ${{ steps.testintelmac.outputs.ramsize }}
    steps:
    - id: testintelmac
      run: |
        hwmemsize=$(sysctl -n hw.memsize)
          # 1024**3 = GB
          ramsize=$(expr $hwmemsize / $((1024**3)))
          echo "ramsize=$ramsize" >> $GITHUB_OUTPUT

  arm64:
    runs-on: macos-14
    needs: [intel, windows, linux]
    env:
      INTEL_RAM: ${{ needs.intel.outputs.size }}
      LINUX_RAM: ${{ needs.linux.outputs.size }}
      WINDOWS_RAM: ${{ needs.windows.outputs.size }}
    steps:
    - name: Test RAM on arm64
      run: |
        hwmemsize=$(sysctl -n hw.memsize)
        # 1024**3 = GB
        ramsize=$(expr $hwmemsize / $((1024**3)))
        echo "macOS:"
        echo "arm64 RAM: ${ramsize} GB"
        echo "intel RAM: $INTEL_RAM GB"
        echo "Win11:"
        echo "windows RAM: $WINDOWS_RAM GB"
        echo "ubuntu:"
        echo "linux RAM: $LINUX_RAM GB"
